/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.theveganrobot.cvcamera.jni;

public interface cvcameraConstants {
  public final static int DO_BIN = cvcameraJNI.DO_BIN_get();
  public final static int DO_THIN = cvcameraJNI.DO_THIN_get();
  public final static int DO_SOLVE = cvcameraJNI.DO_SOLVE_get();
  public final static int DETECT_MSER = cvcameraJNI.DETECT_MSER_get();
}
